@startuml
!include style2.puml
skinparam ArrowFontStyle plain


box <size:35>Logic</size> LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box <size:35>Model</size> MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : <size:30>execute("delete 1")</size>
activate LogicManager

LogicManager -> AddressBookParser : <size:30>parseCommand("delete 1")</size>
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : <size:30>parse("1")</size>
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser
deactivate DeleteCommand

DeleteCommandParser --> AddressBookParser : <size:30></size>
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : <size:30>d</size>
deactivate AddressBookParser

LogicManager -> DeleteCommand : <size:30>execute(m)</size>
activate DeleteCommand

DeleteCommand -> Model : <size:30>deletePerson(1)</size>
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : <size:30>r</size>
deactivate DeleteCommand
DeleteCommand -[hidden]-> DeleteCommandParser
destroy DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
