@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nModel" as Model
CLass "<<interface>>\nFilter" as Filter
Class ModelManager

Class Model

Class ArticleFilter

ModelManager .up.|> Model
ArticleFilter .up.|> Filter
PersonFilter .up.|> Filter
ModelManager --> ArticleFilter : > uses
ModelManager --> PersonFilter : > uses
@enduml
