@startuml
!include style.puml
skinparam ArrowFontStyle plain
scale 2

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ArticleBookParser" as ArticleBookParser LOGIC_COLOR
participant ":SortArticleCommandParser" as SortArticleCommandParser LOGIC_COLOR
participant "s:SortArticleCommand" as SortArticleCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("sort -a d/")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sort -a d/")
activate AddressBookParser

AddressBookParser -> ArticleBookParser : parseCommand("sort d/")
activate ArticleBookParser

create SortArticleCommandParser
ArticleBookParser -> SortArticleCommandParser : SortArticleCommandParser()
activate SortArticleCommandParser

SortArticleCommandParser --> ArticleBookParser
deactivate SortArticleCommandParser

ArticleBookParser -> SortArticleCommandParser : parse("d/")
activate SortArticleCommandParser

create SortArticleCommand
SortArticleCommandParser -> SortArticleCommand : SortArticleCommand("d/")
activate SortArticleCommand

SortArticleCommand --> SortArticleCommandParser
deactivate SortArticleCommand

SortArticleCommandParser --> ArticleBookParser : s
deactivate SortArticleCommandParser
SortArticleCommandParser -[hidden]-> AddressBookParser : s
destroy SortArticleCommandParser

ArticleBookParser --> AddressBookParser : s
deactivate ArticleBookParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> SortArticleCommand : execute()
activate SortArticleCommand

SortArticleCommand -> Model : sortArticleBook("d/")
activate Model

Model --> SortArticleCommand
deactivate Model

SortArticleCommand --> LogicManager : commandResult
deactivate SortArticleCommand
SortArticleCommand -[hidden]-> LogicManager : commandResult
destroy SortArticleCommand

[<--LogicManager : commandResult
deactivate LogicManager
@enduml
