@startuml
!include style2.puml
skinparam ArrowFontStyle plain


box <size:30>Logic</size> LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ArticleBookParser" as ArticleBookParser LOGIC_COLOR
participant ":SortArticleCommandParser" as SortArticleCommandParser LOGIC_COLOR
participant "s:SortArticleCommand" as SortArticleCommand LOGIC_COLOR
end box

box <size:30>Model</size> MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : <size:22>execute("sort -a d/")</size>
activate LogicManager

LogicManager -> AddressBookParser : <size:22>parseCommand("sort -a d/")</size>
activate AddressBookParser

AddressBookParser -> ArticleBookParser : <size:22>parseCommand("sort d/")</size>
activate ArticleBookParser

create SortArticleCommandParser
ArticleBookParser -> SortArticleCommandParser : <size:22>SortArticleCommandParser()</size>
activate SortArticleCommandParser

SortArticleCommandParser --> ArticleBookParser
deactivate SortArticleCommandParser

ArticleBookParser -> SortArticleCommandParser : <size:22>parse("d/")</size>
activate SortArticleCommandParser

create SortArticleCommand
SortArticleCommandParser -> SortArticleCommand : <size:22>SortArticleCommand("d/")</size>
activate SortArticleCommand

SortArticleCommand --> SortArticleCommandParser
deactivate SortArticleCommand

SortArticleCommandParser --> ArticleBookParser : <size:22>s</size>
deactivate SortArticleCommandParser
SortArticleCommandParser -[hidden]-> AddressBookParser : <size:22>s</size>
destroy SortArticleCommandParser

ArticleBookParser --> AddressBookParser : <size:22>s</size>
deactivate ArticleBookParser

AddressBookParser --> LogicManager : <size:22>s</size>
deactivate AddressBookParser

LogicManager -> SortArticleCommand : <size:22>execute()</size>
activate SortArticleCommand

SortArticleCommand -> Model : <size:22>sortArticleBook("d/")</size>
activate Model

Model --> SortArticleCommand
deactivate Model

SortArticleCommand --> LogicManager : <size:22>commandResult</size>
deactivate SortArticleCommand
SortArticleCommand -[hidden]-> LogicManager : <size:22>commandResult</size>
destroy SortArticleCommand

[<--LogicManager : <size:22>commandResult</size>
deactivate LogicManager
@enduml
